#!/usr/bin/env python3
"""Persist the universal drawing tablet settings of the Lua Hyprland config.

Renders the values computed by Quickshell's TabletService as Lua
(`hl.config` for the global tablet options and `hl.device` for every detected
tablet) and writes them to shellOverrides/tablet.lua, the file required by
shellOverrides/main.lua. Writes are atomic and skipped when the file already
matches (Hyprland reloads its config whenever a required file is written),
and main.lua is checked to still carry the require() line for the override.
"""

import argparse
import os
import sys
import tempfile

CONFIG_HOME = os.environ.get("XDG_CONFIG_HOME") or os.path.join(
    os.path.expanduser("~"), ".config"
)
OVERRIDES_DIR = os.path.join(CONFIG_HOME, "hypr", "hyprland", "shellOverrides")
DEFAULT_TABLET_FILE = os.path.join(OVERRIDES_DIR, "tablet.lua")
DEFAULT_MAIN_FILE = os.path.join(OVERRIDES_DIR, "main.lua")

# The line shellOverrides/main.lua uses to pull in the tablet override.
TABLET_REQUIRE = (
    'if is_file_exists(HOME .. "/.config/hypr/hyprland/shellOverrides/tablet.lua") '
    'then require("hyprland.shellOverrides.tablet") end'
)
TABLET_REQUIRE_MARKER = 'require("hyprland.shellOverrides.tablet")'

HEADER = (
    "-- Universal drawing tablet configuration generated by Quickshell\n"
    "-- DO NOT EDIT DIRECTLY. This file is managed by TabletService\n"
    "\n"
)


def fmt(value):
    """Render a number the way Lua likes it: 204.8, 10.67, 0."""
    return f"{float(value):.3f}".rstrip("0").rstrip(".") or "0"


def lua_str(value):
    return str(value).replace("\\", "\\\\").replace('"', '\\"')


def device_block(name, output, transform, size, position):
    return (
        "hl.device({\n"
        f'    name = "{lua_str(name)}",\n'
        f'    output = "{lua_str(output)}",\n'
        f"    transform = {int(transform)},\n"
        f"    active_area_size = {{ {fmt(size[0])}, {fmt(size[1])} }},\n"
        f"    active_area_position = {{ {fmt(position[0])}, {fmt(position[1])} }},\n"
        "})\n\n"
    )


def build_lua(device_names, output, transform, size, position, device_areas):
    """Build the whole tablet.lua contents."""
    lines = [
        HEADER,
        "hl.config({\n",
        "    input = {\n",
        "        tablet = {\n",
        f'            output = "{lua_str(output)}",\n',
        f"            transform = {int(transform)},\n",
        f"            active_area_size = {{ {fmt(size[0])}, {fmt(size[1])} }},\n",
        f"            active_area_position = {{ {fmt(position[0])}, {fmt(position[1])} }},\n",
        "        }\n",
        "    }\n",
        "})\n\n",
    ]
    for name in device_names:
        if not name:
            continue
        area = device_areas.get(name, (size[0], size[1], position[0], position[1]))
        lines.append(device_block(name, output, transform, area[:2], area[2:]))
    return "".join(lines)


def atomic_write(path, content):
    directory = os.path.dirname(path) or "."
    os.makedirs(directory, exist_ok=True)
    fd, tmp_path = tempfile.mkstemp(dir=directory, prefix=".tablet-", suffix=".lua")
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as handle:
            handle.write(content)
        os.replace(tmp_path, path)
    except BaseException:
        if os.path.exists(tmp_path):
            os.unlink(tmp_path)
        raise


def write_if_changed(path, content):
    """Write `content` to `path` only when it differs; True when written.

    Hyprland's ConfigWatcher watches every file the config requires and
    reacts to *any* inotify event for them (including the IN_IGNORED that an
    atomic replace of a watched inode produces) with a full config reload.
    Since TabletService re-applies on every `configreloaded`, rewriting an
    identical tablet.lua would spin forever: write -> reload ->
    configreloaded -> apply -> write -> ...  Comparing first keeps one write
    per real settings change and none on shell or config restarts.
    """
    try:
        with open(path, "r", encoding="utf-8") as handle:
            if handle.read() == content:
                return False
    except (FileNotFoundError, UnicodeDecodeError):
        pass
    atomic_write(path, content)
    return True


def ensure_main_requires(main_file):
    """Make sure main.lua pulls in the tablet override."""
    try:
        with open(main_file, "r", encoding="utf-8") as handle:
            content = handle.read()
    except FileNotFoundError:
        return False

    if TABLET_REQUIRE_MARKER in content:
        return False

    new_content = content
    if new_content and not new_content.endswith("\n"):
        new_content += "\n"
    new_content += TABLET_REQUIRE + "\n"
    return write_if_changed(main_file, new_content)


def parse_args(argv=None):
    parser = argparse.ArgumentParser(
        description="Write the persistent drawing tablet override for Hyprland."
    )
    parser.add_argument("--file", default=DEFAULT_TABLET_FILE, help="target lua file")
    parser.add_argument(
        "--main-file", default=DEFAULT_MAIN_FILE, help="shellOverrides/main.lua to check"
    )
    parser.add_argument(
        "--device", action="append", default=[], dest="devices", help="tablet name (repeatable)"
    )
    parser.add_argument(
        "--device-area",
        action="append",
        default=[],
        nargs=5,
        metavar=("NAME", "WIDTH", "HEIGHT", "X", "Y"),
        help="per tablet active area in mm, overriding --active-area-size/position",
    )
    parser.add_argument("--output", default="", help='monitor name, "" maps across all monitors')
    parser.add_argument("--transform", type=int, default=0, choices=range(0, 7), help="rotation")
    parser.add_argument(
        "--active-area-size",
        type=float,
        nargs=2,
        default=[0.0, 0.0],
        metavar=("WIDTH", "HEIGHT"),
        help="active area size in mm",
    )
    parser.add_argument(
        "--active-area-position",
        type=float,
        nargs=2,
        default=[0.0, 0.0],
        metavar=("X", "Y"),
        help="active area offset in mm",
    )
    parser.add_argument(
        "--no-ensure-main",
        action="store_true",
        help="do not touch main.lua",
    )
    return parser.parse_args(argv)


def main(argv=None):
    args = parse_args(argv)

    device_areas = {}
    for name, width, height, x, y in args.device_area:
        device_areas[name] = (float(width), float(height), float(x), float(y))

    devices = list(dict.fromkeys(args.devices + list(device_areas.keys())))

    write_if_changed(
        args.file,
        build_lua(
            devices,
            args.output,
            args.transform,
            tuple(args.active_area_size),
            tuple(args.active_area_position),
            device_areas,
        ),
    )

    if not args.no_ensure_main:
        ensure_main_requires(args.main_file)

    return 0


if __name__ == "__main__":
    sys.exit(main())
